[source]
type = "UtxoRpc"
endpoint = "https://mainnet.utxorpc-v0.demeter.run"

[[filters]]
type = "Deno"
main_js = "reducer.js"
use_async = true

[sink]
type = "SqlTable"
mode = "SlotSeries"
table = "my_reducer_1"
connection = "sqlite://scrolls.db"
